# UI 佈局常數
# 集中定義，供 ui.py 與各 ui_mixins 共用，避免循環 import

WINDOW_DEFAULT_WIDTH = 1100
WINDOW_DEFAULT_HEIGHT = 750
WINDOW_MIN_WIDTH = 950
WINDOW_MIN_HEIGHT = 600

SIDEBAR_FULL_WIDTH = 341
SIDEBAR_MIN_WIDTH = 60
SIDEBAR_WIDTH = 280
ACTIVITY_BAR_WIDTH = 60

PROGRESS_BAR_WIDTH = 150
START_BUTTON_MIN_WIDTH = 150

INPUT_START_ROW_MAX_WIDTH = 80
INPUT_END_ROW_MAX_WIDTH = 100
INPUT_COL_MAX_WIDTH = 60

SWAP_BUTTON_SIZE = 32
SWAP_ICON_SIZE = 20
